rvm:
  - 2.0
  - 2.1
  - 2.2
script:
  - bundle exec foodcritic -f any . --tags ~FC007 --tags ~FC023 --tags ~FC024 --tags ~FC048
  # - bundle exec rspec --color --format progress
  - bundle exec rubocop -l
